# -*- coding: utf-8 -*-
"""
SoloEngine : 默认MCP和Skills包数据模块

@file default_packages.py
@description 默认MCP和Skills包配置数据 - 基于网络搜索获取的权威MCP服务器和Skills包
@author Sh4rlock
@date 2026-04-09

功能描述：
本模块提供以下核心功能：
    - 默认MCP服务器配置
    - 默认Skills包配置
    - 社区精选工具和服务

依赖:
    - 无（纯数据定义）

使用示例:
    - from app.utils.default_packages import DEFAULT_MCP_SERVERS, DEFAULT_SKILLS_PACKAGES
    - for server in DEFAULT_MCP_SERVERS:
    -     print(server["name"])

数据来源:
    - MCP服务器: Anthropic官方 @modelcontextprotocol/servers
    - MCP服务器: GitHub官方 github-mcp-server
    - MCP服务器: awesome-mcp-servers社区精选
    - Skills包: Anthropic官方 @anthropics/skills
    - Skills包: awesome-claude-skills社区精选
"""

DEFAULT_MCP_SERVERS = [
    {
        "name": "Filesystem MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-filesystem"],
        "description": "安全文件操作，支持可配置的访问控制。提供文件读写、目录管理、搜索等功能。",
        "tags": ["filesystem", "file", "official", "anthropic"],
        "timeout": 30,
        "author": "SoloEngine",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "GitHub MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-github"],
        "description": "GitHub仓库管理、文件操作和API集成。支持Issue管理、PR处理、代码搜索等。",
        "tags": ["github", "git", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Git MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-git"],
        "description": "Git仓库读取、搜索和操作。支持分支管理、提交历史查看、diff分析等。",
        "tags": ["git", "version-control", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "PostgreSQL MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-postgres"],
        "description": "PostgreSQL数据库只读访问和模式检查。支持SQL查询、表结构分析等。",
        "tags": ["database", "postgresql", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "SQLite MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-sqlite"],
        "description": "SQLite数据库交互和商业智能。支持数据库查询、表管理、数据分析等。",
        "tags": ["database", "sqlite", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Memory MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-memory"],
        "description": "基于知识图的持久化记忆系统。支持实体关系存储、记忆检索等。",
        "tags": ["memory", "knowledge-graph", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Fetch MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-fetch"],
        "description": "Web内容获取和转换，优化LLM使用。支持HTML转Markdown、网页抓取等。",
        "tags": ["web", "fetch", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Sequential Thinking MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"],
        "description": "通过思维序列进行动态和反思性问题解决。支持复杂问题拆解、步骤推理等。",
        "tags": ["thinking", "reasoning", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Time MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-time"],
        "description": "时间和时区转换功能。支持当前时间获取、时区转换、时间计算等。",
        "tags": ["time", "timezone", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Puppeteer MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-puppeteer"],
        "description": "浏览器自动化和网页抓取。支持页面导航、截图、表单填写、JS执行等。",
        "tags": ["browser", "automation", "official", "anthropic"],
        "timeout": 60,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Brave Search MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-brave-search"],
        "description": "使用Brave搜索API进行网络和本地搜索。隐私优先的搜索引擎集成。",
        "tags": ["search", "web", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Google Maps MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-google-maps"],
        "description": "位置服务、路线和地点详情。支持地理编码、路线规划、POI搜索等。",
        "tags": ["maps", "location", "google", "official"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Slack MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-slack"],
        "description": "Slack频道管理和消息功能。支持消息发送、频道管理、团队协作等。",
        "tags": ["slack", "communication", "official", "anthropic"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Google Drive MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-gdrive"],
        "description": "Google Drive文件访问和搜索。支持文件列表、搜索、下载等操作。",
        "tags": ["google", "drive", "storage", "official"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/modelcontextprotocol/servers",
    },
    {
        "name": "Everything Search MCP",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@mamertofabian/mcp-everything-search"],
        "description": "Windows快速文件搜索工具。使用Everything SDK实现毫秒级文件定位。",
        "tags": ["search", "files", "windows", "community"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/mamertofabian/mcp-everything-search",
    },
    {
        "name": "Playwright MCP Server",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@executeautomation/playwright-mcp-server"],
        "description": "使用Playwright进行浏览器自动化。支持多浏览器、截图、表单操作等。",
        "tags": ["browser", "playwright", "automation", "community"],
        "timeout": 60,
        "author": "System",
        "source": "https://github.com/executeautomation/playwright-mcp-server",
    },
    {
        "name": "Notion MCP Server",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@notion/mcp-server-notion"],
        "description": "Notion工作区集成。支持页面管理、数据库操作、内容搜索等。",
        "tags": ["notion", "productivity", "community"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/makenotion/notion-mcp-server",
    },
    {
        "name": "MongoDB MCP Server",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@mongodb/mcp-server"],
        "description": "MongoDB官方MCP服务器。支持数据库探索、集合查询、文档操作等。",
        "tags": ["mongodb", "database", "nosql", "official"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/mongodb-js/mcp-server",
    },
    {
        "name": "Linear MCP Server",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@linear/mcp-server-linear"],
        "description": "Linear项目管理集成。支持问题跟踪、项目管理、团队协作等。",
        "tags": ["linear", "project-management", "issues", "community"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/linear/linear-mcp-server",
    },
    {
        "name": "Kubernetes MCP Server",
        "transport": "stdio",
        "command": "python",
        "args": ["-m", "mcp_k8s_server"],
        "description": "Kubernetes集群管理。支持Pod管理、部署操作、资源监控等。",
        "tags": ["kubernetes", "k8s", "devops", "community"],
        "timeout": 30,
        "author": "System",
        "source": "https://github.com/guolisen/mcp_k8s_server",
    },
]

DEFAULT_SKILLS_PACKAGES = [
    {
        "name": "docx",
        "description": "Word文档处理技能包。支持创建、编辑、格式化DOCX文档，自动生成专业报告。",
        "author": "System",
        "tags": ["document", "word", "docx", "official"],
        "instructions": "你是Word文档处理专家。创建文档时请确保：1. 格式规范统一 2. 样式层次分明 3. 目录自动生成 4. 页眉页脚设置 5. 图表编号管理",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "pdf",
        "description": "PDF文档处理技能包。支持PDF解析、合并、提取和转换。",
        "author": "System",
        "tags": ["document", "pdf", "official"],
        "instructions": "你是PDF处理专家。处理PDF时请关注：1. 文本提取准确性 2. 表格识别 3. 图片处理 4. 元数据管理 5. 格式转换质量",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "pptx",
        "description": "PowerPoint演示文稿技能包。支持自动生成专业PPT、模板应用和内容排版。",
        "author": "System",
        "tags": ["document", "powerpoint", "pptx", "official"],
        "instructions": "你是PPT设计专家。创建演示文稿时请确保：1. 主题风格统一 2. 内容层次清晰 3. 图表可视化 4. 动画适度 5. 演讲者备注完善",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "xlsx",
        "description": "Excel电子表格技能包。支持数据分析、图表生成和公式计算。",
        "author": "System",
        "tags": ["document", "excel", "xlsx", "data", "official"],
        "instructions": "你是Excel专家。处理电子表格时请关注：1. 数据清洗和验证 2. 公式和函数使用 3. 数据透视表 4. 图表可视化 5. 条件格式应用",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "frontend-design",
        "description": "前端设计技能包。提供React/Vue等框架的最佳实践和UI设计指南。",
        "author": "System",
        "tags": ["frontend", "design", "react", "vue", "official"],
        "instructions": "你是前端设计专家。设计界面时请关注：1. 响应式布局 2. 组件复用性 3. 状态管理 4. 性能优化 5. 可访问性标准",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "mcp-builder",
        "description": "MCP服务器构建技能包。帮助快速创建和部署MCP服务器。",
        "author": "System",
        "tags": ["mcp", "server", "development", "official"],
        "instructions": "你是MCP开发专家。构建MCP服务器时请关注：1. 工具定义规范 2. 输入输出Schema 3. 错误处理机制 4. 安全性考虑 5. 文档完整性",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "skill-creator",
        "description": "技能创建器。帮助用户创建自定义Skills包的元技能。",
        "author": "System",
        "tags": ["skill", "creator", "meta", "official"],
        "instructions": "你是Skill创建专家。创建新技能时请确保：1. 清晰的触发条件 2. 完整的指令描述 3. 示例和模板 4. 渐进式披露设计 5. 可维护性",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "webapp-testing",
        "description": "Web应用测试技能包。支持端到端测试、单元测试和集成测试。",
        "author": "System",
        "tags": ["testing", "web", "e2e", "official"],
        "instructions": "你是Web测试专家。编写测试时请关注：1. 测试覆盖率 2. 边界条件 3. 异常处理 4. 性能测试 5. 跨浏览器兼容",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "algorithmic-art",
        "description": "算法艺术生成技能包。使用p5.js创建生成式艺术作品。",
        "author": "System",
        "tags": ["art", "creative", "p5js", "official"],
        "instructions": "你是生成艺术专家。创作时请关注：1. 算法美学 2. 参数化设计 3. 随机性与控制 4. 交互性 5. 性能优化",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "brand-guidelines",
        "description": "品牌指南技能包。帮助维护品牌一致性和视觉规范。",
        "author": "System",
        "tags": ["brand", "design", "guidelines", "official"],
        "instructions": "你是品牌设计专家。维护品牌时请确保：1. 颜色规范 2. 字体使用 3. Logo规范 4. 语调一致 5. 视觉元素统一",
        "source": "https://github.com/anthropics/skills",
    },
    {
        "name": "code-review",
        "description": "代码审查技能包。自动分析代码质量、发现潜在问题并提供改进建议。",
        "author": "System",
        "tags": ["coding", "review", "quality", "community"],
        "instructions": "你是专业代码审查专家。审查代码时请关注：1. 代码质量和可读性 2. 潜在的bug和错误 3. 性能优化建议 4. 安全漏洞 5. 最佳实践遵循情况",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "technical-writing",
        "description": "技术文档写作技能包。帮助生成清晰、专业的技术文档。",
        "author": "System",
        "tags": ["writing", "documentation", "technical", "community"],
        "instructions": "你是技术文档写作专家。编写文档时请确保：1. 结构清晰，层次分明 2. 语言简洁准确 3. 包含必要的代码示例 4. 提供使用说明和注意事项",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "api-design",
        "description": "API设计技能包。帮助设计RESTful API和生成API文档。",
        "author": "System",
        "tags": ["api", "design", "rest", "community"],
        "instructions": "你是API设计专家。设计API时请遵循：1. RESTful设计原则 2. 统一的命名规范 3. 合理的状态码使用 4. 完整的错误处理 5. 版本控制策略",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "testing-assistant",
        "description": "测试辅助技能包。帮助编写单元测试、集成测试和端到端测试。",
        "author": "System",
        "tags": ["testing", "unit-test", "qa", "community"],
        "instructions": "你是测试专家。编写测试时请确保：1. 覆盖正常和异常情况 2. 测试用例独立且可重复 3. 使用有意义的测试名称 4. 模拟外部依赖 5. 验证边界条件",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "git-workflow",
        "description": "Git工作流技能包。提供Git最佳实践和分支管理策略。",
        "author": "System",
        "tags": ["git", "version-control", "workflow", "community"],
        "instructions": "你是Git工作流专家。建议遵循：1. 功能分支开发模式 2. 有意义的提交信息 3. 合理的分支命名 4. 代码审查流程 5. 版本标签管理",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "python-best-practices",
        "description": "Python最佳实践技能包。提供Python编码规范和优化建议。",
        "author": "System",
        "tags": ["python", "best-practices", "coding", "community"],
        "instructions": "你是Python专家。请遵循：1. PEP 8编码规范 2. 类型注解 3. 文档字符串 4. 异常处理最佳实践 5. 性能优化技巧 6. 代码组织结构",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "database-design",
        "description": "数据库设计技能包。帮助设计数据库模式和优化查询。",
        "author": "System",
        "tags": ["database", "sql", "design", "community"],
        "instructions": "你是数据库设计专家。请遵循：1. 范式设计原则 2. 合理的索引策略 3. 查询优化技巧 4. 数据完整性约束 5. 备份和恢复策略",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "security-audit",
        "description": "安全审计技能包。帮助识别代码中的安全漏洞。",
        "author": "System",
        "tags": ["security", "audit", "vulnerability", "community"],
        "instructions": "你是安全审计专家。请检查：1. SQL注入风险 2. XSS漏洞 3. CSRF保护 4. 敏感数据处理 5. 认证授权机制 6. 输入验证",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "docker-deployment",
        "description": "Docker部署技能包。帮助容器化应用和编写Dockerfile。",
        "author": "System",
        "tags": ["docker", "container", "deployment", "community"],
        "instructions": "你是Docker专家。请关注：1. 多阶段构建 2. 最小化镜像大小 3. 安全最佳实践 4. 环境变量管理 5. 健康检查配置 6. 日志处理",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
    {
        "name": "data-analysis",
        "description": "数据分析技能包。帮助进行数据清洗、分析和可视化。",
        "author": "System",
        "tags": ["data", "analysis", "visualization", "community"],
        "instructions": "你是数据分析专家。请关注：1. 数据清洗和预处理 2. 探索性数据分析 3. 统计分析方法 4. 可视化最佳实践 5. 结果解释和报告",
        "source": "https://github.com/ComposioHQ/awesome-claude-skills",
    },
]
