import { APP_CONFIG } from './index';

export const LLM_DEFAULTS = {
  TEMPERATURE:       APP_CONFIG.LLM_DEFAULT_TEMPERATURE,
  MAX_TOKENS:        APP_CONFIG.LLM_DEFAULT_MAX_TOKENS,
  MAX_TOKENS_LIMIT:  APP_CONFIG.LLM_MAX_TOKENS_LIMIT,
  TOP_P:             APP_CONFIG.LLM_DEFAULT_TOP_P,
  FREQUENCY_PENALTY: APP_CONFIG.LLM_DEFAULT_FREQUENCY_PENALTY,
  PRESENCE_PENALTY:  APP_CONFIG.LLM_DEFAULT_PRESENCE_PENALTY,
  TIMEOUT:           APP_CONFIG.LLM_DEFAULT_TIMEOUT,
  // 工具调用轮次默认值：一次 react_core 循环中 agent 允许调用 LLM API 的次数上限
  MAX_TOOL_CALLS:    APP_CONFIG.LLM_DEFAULT_MAX_TOOL_CALLS,
};
