import { APP_CONFIG } from './index';

export const LLM_DEFAULTS = {
  TEMPERATURE:       APP_CONFIG.LLM_DEFAULT_TEMPERATURE,
  MAX_TOKENS:        APP_CONFIG.LLM_DEFAULT_MAX_TOKENS,
  MAX_TOKENS_LIMIT:  APP_CONFIG.LLM_MAX_TOKENS_LIMIT,
  TOP_P:             APP_CONFIG.LLM_DEFAULT_TOP_P,
  FREQUENCY_PENALTY: APP_CONFIG.LLM_DEFAULT_FREQUENCY_PENALTY,
  PRESENCE_PENALTY:  APP_CONFIG.LLM_DEFAULT_PRESENCE_PENALTY,
  TIMEOUT:           APP_CONFIG.LLM_DEFAULT_TIMEOUT,
};
