import { APP_CONFIG } from './index';

export const WEBSOCKET_CONFIG = {
  RECONNECT_INTERVAL_MS:        APP_CONFIG.WS_RECONNECT_INTERVAL_MS,
  MAX_RECONNECT_ATTEMPTS:       APP_CONFIG.WS_MAX_RECONNECT_ATTEMPTS,
  HEARTBEAT_INTERVAL_MS:        APP_CONFIG.WS_HEARTBEAT_INTERVAL_MS,
  HEARTBEAT_TIMEOUT_MS:         APP_CONFIG.WS_HEARTBEAT_TIMEOUT_MS,
  HEARTBEAT_CHECK_INTERVAL_MS:  APP_CONFIG.WS_HEARTBEAT_CHECK_INTERVAL_MS,
  MAX_RECONNECT_DELAY_MS:       APP_CONFIG.WS_MAX_RECONNECT_DELAY_MS,
  EXECUTION_TIMEOUT:            APP_CONFIG.WS_EXECUTION_TIMEOUT,
  RESPONSE_TIMEOUT:             APP_CONFIG.WS_RESPONSE_TIMEOUT,
};
