# -*- coding: utf-8 -*-
"""
MCP Service 配置模块。
"""

import os
from typing import Optional

MCP_SERVICE_PORT = 8992
MCP_SERVICE_HOST = "0.0.0.0"

DATABASE_PATH = os.path.join(
    os.path.dirname(__file__), 
    "..", "..", "data", "mcp_service", "mcp_service.db"
)

MCP_SERVERS_STORAGE_DIR = os.path.join(
    os.path.dirname(__file__),
    "..", "storage", "mcp_servers"
)

DEFAULT_TIMEOUT = 30
MAX_TOOL_ARGUMENTS_SIZE = 1024 * 1024

CORS_ORIGINS = [
    "http://localhost:8991",
    "http://127.0.0.1:8991",
    "http://localhost:8990",
    "http://127.0.0.1:8990",
]

OPEN_SOURCE_MCPS = [
    {
        "id": "filesystem",
        "name": "Filesystem",
        "description": "文件系统操作工具，支持读写文件、目录管理",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/allowed/dir"],
        "category": "file",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["file", "filesystem", "local"],
    },
    {
        "id": "github",
        "name": "GitHub",
        "description": "GitHub 仓库和 issue 操作",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-github"],
        "env": {"GITHUB_PERSONAL_ACCESS_TOKEN": "your_github_token"},
        "category": "dev",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["github", "git", "repository"],
    },
    {
        "id": "postgres",
        "name": "PostgreSQL",
        "description": "PostgreSQL 数据库操作",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-postgres"],
        "env": {"POSTGRES_CONNECTION_STRING": "postgresql://user:pass@host:port/db"},
        "category": "database",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["database", "postgresql", "sql"],
    },
    {
        "id": "sqlite",
        "name": "SQLite",
        "description": "SQLite 数据库操作",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-sqlite", "--db-path", "/path/to/db.sqlite"],
        "category": "database",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["database", "sqlite", "sql"],
    },
    {
        "id": "brave-search",
        "name": "Brave Search",
        "description": "Brave 搜索引擎集成",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-brave-search"],
        "env": {"BRAVE_API_KEY": "your_brave_api_key"},
        "category": "search",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["search", "web", "brave"],
    },
    {
        "id": "puppeteer",
        "name": "Puppeteer",
        "description": "浏览器自动化工具",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-puppeteer"],
        "category": "browser",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["browser", "automation", "puppeteer"],
    },
    {
        "id": "slack",
        "name": "Slack",
        "description": "Slack 集成",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-slack"],
        "env": {"SLACK_BOT_TOKEN": "xoxb-your-bot-token", "SLACK_TEAM_ID": "T01234567"},
        "category": "communication",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["slack", "communication", "messaging"],
    },
    {
        "id": "memory",
        "name": "Memory",
        "description": "知识图谱记忆存储",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-memory"],
        "category": "ai",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["memory", "knowledge", "ai"],
    },
    {
        "id": "fetch",
        "name": "Fetch",
        "description": "HTTP请求工具，支持GET/POST等操作",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-fetch"],
        "category": "http",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["http", "fetch", "api"],
    },
    {
        "id": "git",
        "name": "Git",
        "description": "Git版本控制操作",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-git"],
        "category": "dev",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["git", "version-control", "dev"],
    },
    {
        "id": "google-maps",
        "name": "Google Maps",
        "description": "Google地图服务集成",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-google-maps"],
        "env": {"GOOGLE_MAPS_API_KEY": "your_api_key"},
        "category": "location",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["maps", "location", "google"],
    },
    {
        "id": "google-drive",
        "name": "Google Drive",
        "description": "Google Drive文件存储集成",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-gdrive"],
        "category": "storage",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["google", "drive", "storage"],
    },
    {
        "id": "everart",
        "name": "EverArt",
        "description": "AI图像生成工具",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-everart"],
        "env": {"EVERART_API_KEY": "your_api_key"},
        "category": "ai",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["ai", "image", "generation"],
    },
    {
        "id": "sequential-thinking",
        "name": "Sequential Thinking",
        "description": "顺序思考推理工具",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"],
        "category": "ai",
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "tags": ["ai", "reasoning", "thinking"],
    },
    {
        "id": "playwright",
        "name": "Playwright",
        "description": "浏览器自动化测试工具",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@playwright/mcp"],
        "category": "browser",
        "author": "Microsoft",
        "source": "https://github.com/microsoft/playwright",
        "tags": ["browser", "automation", "testing"],
    },
    {
        "id": "docker",
        "name": "Docker",
        "description": "Docker容器管理",
        "transport": "stdio",
        "command": "docker",
        "args": ["mcp-server-docker"],
        "category": "devops",
        "author": "Community",
        "source": "https://github.com/docker/mcp-server-docker",
        "tags": ["docker", "container", "devops"],
    },
    {
        "id": "aws",
        "name": "AWS",
        "description": "Amazon Web Services集成",
        "transport": "stdio",
        "command": "uvx",
        "args": ["awslabs.aws-mcp-server-cli"],
        "category": "cloud",
        "author": "AWS",
        "source": "https://github.com/awslabs/mcp",
        "tags": ["aws", "cloud", "infrastructure"],
    },
    {
        "id": "kubernetes",
        "name": "Kubernetes",
        "description": "Kubernetes集群管理",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "kubernetes-mcp-server"],
        "category": "devops",
        "author": "Community",
        "source": "https://github.com/manusa/kubernetes-mcp-server",
        "tags": ["kubernetes", "k8s", "devops"],
    },
    {
        "id": "mongodb",
        "name": "MongoDB",
        "description": "MongoDB数据库操作",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "mongodb-mcp-server"],
        "env": {"MONGODB_URI": "mongodb://localhost:27017"},
        "category": "database",
        "author": "Community",
        "source": "https://github.com/kiliczsh/mongodb-mcp-server",
        "tags": ["database", "mongodb", "nosql"],
    },
    {
        "id": "redis",
        "name": "Redis",
        "description": "Redis缓存服务",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "redis-mcp-server"],
        "env": {"REDIS_URL": "redis://localhost:6379"},
        "category": "database",
        "author": "Community",
        "source": "https://github.com/redis/mcp-redis",
        "tags": ["database", "redis", "cache"],
    },
]

DEFAULT_MCP_SERVERS = [
    {
        "name": "Filesystem",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-filesystem", "./"],
        "env": {},
        "timeout": 30,
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "description": "文件系统操作工具，支持读写文件、目录管理",
        "tags": ["file", "filesystem", "local"],
    },
    {
        "name": "Memory",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-memory"],
        "env": {},
        "timeout": 30,
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "description": "知识图谱记忆存储，支持持久化记忆",
        "tags": ["memory", "knowledge", "ai"],
    },
    {
        "name": "Fetch",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-fetch"],
        "env": {},
        "timeout": 30,
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "description": "HTTP请求工具，支持GET/POST等操作",
        "tags": ["http", "fetch", "api"],
    },
    {
        "name": "Sequential Thinking",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"],
        "env": {},
        "timeout": 30,
        "author": "Anthropic",
        "source": "https://github.com/modelcontextprotocol/servers",
        "description": "顺序思考推理工具",
        "tags": ["ai", "reasoning", "thinking"],
    },
]
